### PR TITLE
#227 fix setting css style `touch-action: none`

### PR DESCRIPTION
**Pull request by al-fyodorov**
Fix error because which mobile browsers not use touch actions with component Draggable.

https://github.com/mzabriskie/react-draggable/issues/227
https://github.com/STRML/react-grid-layout/issues/637

### CODE REVIEW

**Comment by tomhollander** [comment]
+1 to merge this, to fix the linked issue which has been open for 2 years.

**Comment by Worik42** [comment]
+1 to merge.

**Comment by newsiberian** [comment]
@STRML, please, merge this

**Comment by STRML** [comment]
Fixed in #470

**Pull request closed without merging**
