### PR TITLE
Update react to 0.14.0

### PR DESCRIPTION
**Pull request by takumi0h**

### CODE REVIEW

**Comment by scherler** [comment]
Hi the patch looks good, can we do something to give you a helping hand?

**Comment by tony99nyr** [comment]
+1

**Comment by GirlBossRush** [comment]
+1 would love to see this get merged.

Cheers

**Comment by ludomathieu** [comment]
+1

**Comment by stoeffel** [comment]
LGTM, I tested this PR-branch in our application. @mzabriskie Can I help you to get this merged?

**Comment by STRML** [comment]
This is fixed in `v1.0.0`.

**Pull request closed without merging**
