### PR TITLE
AppVeyor configuration

### PR DESCRIPTION
**Pull request by paazmaya**
Just have to try if the environment variable gets set correctly...

In order to try it out, the service needs to be enabled by the owner @mzabriskie

### CODE REVIEW

**Comment by paazmaya** [comment]
Tested here to get the correct environment variable
https://ci.appveyor.com/project/paazmaya/image-duplicate-remover/build/job/f11lc6s6homw3vdy

**Comment by paazmaya** [comment]
Any reason that might be blocking this?

**Comment by mzabriskie** [comment]
AppVeyor has been enabled.

**Comment by paazmaya** [comment]
Any chance of getting this merged?

**Comment by STRML** [comment]
Unfortunately this is blocked on @mzabriskie.

**Comment by paazmaya** [comment]
Ok, so AppVeyor has been enabled for this repository, but it probably never has ran since the configuration file is so far missing.

**Comment by STRML** [comment]
My apologies, didn't see the comment above (was following through email). Merging.

**Comment by paazmaya** [comment]
Thank you!

**Pull request merged**
