### PR TITLE
Fix for latest iPad scrolling instead of dragging vertically.

### PR DESCRIPTION
**Pull request by JaneCoder**
This is a fix for iPad, which has a flaw with vertical dragging related to the scroll bar. Other touch devices, even iPhone worked fine without the fix. This version uses the event helpers to add and remove the events.

### CODE REVIEW

**Comment by JaneCoder** [comment]
Unfortunately this version is failing for vertical drag on Lenovo touch screens in Firefox now. We will do some more testing and try to determine the cause.

**Comment by STRML** [comment]
I appreciate your tenacity! Browsers implement this spec very badly.

**Comment by JaneCoder** [comment]
This is looking good. We found that the tester had issues outside of our app with touch on chrome and firefox. Touch had to be re-enabled on her device. It was not related to the update to the ipad fix.

**Comment by STRML** [comment]
I'm going to review this when I get home - have an iPad laying around - I'll update when I am sure this is working. Thanks!

**Comment by JaneCoder** [comment]
Thank you for your wonderful work!

**Comment by JaneCoder** [comment]
Hello @STRML. Have you had a chance to test with your ipad? Please let me know if there is anything different you'd like me to do.

**Comment by nisjunk** [comment]
On iPadPro, all demos fail because the whole page also scrolls with the element. I think it is a show stopper issue.

**Comment by JaneCoder** [comment]
nisjunk, we have that issue with the original version, but not with this patched version which stops scrolling on drag.

PS we are using a version of this pull request from our bitbucket repo, and will continue with our own patched version until this is accepted or someone else puts in a fix the owners like.

**Comment by STRML** [comment]
Hi @JaneCoder,

Very sorry for how long it took to get to this.

I reviewed your fix and found that it fixed most use cases, but caused issues with bounded elements. After spending some time reviewing exactly how iOS handles touch events, I was able to very simply fix this in 8a51de9.

Thanks for reporting this!

**Comment by STRML** [comment]
This is published and in `v2.2.3`.

**Comment by JaneCoder** [comment]
Sweet! Thanks so very much!

**Pull request closed without merging**
