### PR TITLE
fixed sticky click on IE11/Edge

### PR DESCRIPTION
**Pull request by ibio**
Using IE, Edge(13, 14 and 15), if this react-draggable is in an iframe, the draggable item gets 'stuck' on the mouse if the user attempts to drag it off iframe/screen.

To reproduce:
1 Make sure react-draggable is in an iframe
2 Open IE browser 
3 Try to click/drag the draggable item out of the iframe
4 Release mouse click(outside of the iframe). Observe as the user now moves mouse around the screen, the draggable item follows as if it's stuck to the pointer.

### CODE REVIEW

**Comment by ibio** [comment]
@STRML hey, can you please have a look this PR? Thanks :)

**Comment by STRML** [comment]
I don't believe this is guaranteed to succeed if `top` is cross-origin, which will break this for other users.

**Comment by ibio** [comment]
Good point! if I use `try catch` first, and use `ownerDocument` as a backup, will that be acceptable?

**Comment by ibio** [comment]
Use a new PR to track this issue.

**Pull request closed without merging**
