### PR TITLE
Adds detection of SVGElements and uses appropriate transform attribute.

### PR DESCRIPTION
**Pull request by martinRoss**
IE does not support transforming SVGElements via the style attribute and requires the change to be via the transform attribute. Other browsers also respect these attributes so it should not break elsewhere.

Added tests for both SVG detection and proper use of SVG transforms. Let me know if you'd like to see anything else!

### CODE REVIEW

**Comment by psaia** [comment]
Awesome!

**Comment by STRML** [comment]
Thanks! This has some conflicts, most probably in the dist files, so I'll need to pull it and commit separately.

**Comment by STRML** [comment]
@martinRoss Could you rebase on master?

**Comment by martinRoss** [comment]
Sure thing, I'll rebase and put in a new pull request. You might still have
some issue with the dist files though.

**Comment by STRML** [comment]
Doesn't need to be a new PR, you could just rework this one. Just skip the dist files entirely or regenerate them in the last commit.

**Comment by martinRoss** [comment]
Ah, whoops, still new to PRs--created a new one. Regenerated the dist files
in the last commit.

**Pull request closed without merging**
