### PR TITLE
Add rem example, closes #480

### LINKED ISSUE #480: Using rem as unit in transforms
Draggable works just as I need, with one exception. The CSS transforms are done with pixels, but I need them to be rems, as my application uses them for scaling stuff down 1:1. Pretty much everything in my app with a pixel unit is converted with this little helper: (x) => `${x / 16}rem`

Is it possible to change those without ditching the batteries and using DraggableCore? I took a quick peek at the source and looks like no, this requires some changes. 

```typescript

export function getTranslation({x, y}: ControlPosition, positionOffset: PositionOffsetControlPosition, unitSuffix: string): string {
  let translation = `translate(${x}${unitSuffix},${y}${unitSuffix})`;
  if (positionOffset) {
    const defaultX = `${(typeof positionOffset.x === 'string') ? positionOffset.x : positionOffset.x + unitSuffix}`;
    const defaultY = `${(typeof positionOffset.y === 'string') ? positionOffset.y : positionOffset.y + unitSuffix}`;
    translation = `translate(${defaultX}, ${defaultY})` + translation;
  }
  return translation;
}
```

Maybe with a `customizer` that takes the translation and params used to build it, and does whatever it wants with it? Not everyone is using 16 as the baseline value so it might be hard to support rems directly, so this might be an ok compromise. 

```typescript

export function getTranslation({x, y}: ControlPosition, positionOffset: PositionOffsetControlPosition, unitSuffix: string, customizer?: (translation: string, xy: ControlPosition, offset: PositionOffsetControlPosition, unitSuffix: string) => string): string {
  let translation = `translate(${x}${unitSuffix},${y}${unitSuffix})`;

  if (customizer) {
    return customizer(translation, { x, y }, positionOffset, unitSuffix)
  }

  if (positionOffset) {
    const defaultX = `${(typeof positionOffset.x === 'string') ? positionOffset.x : positionOffset.x + unitSuffix}`;
    const defaultY = `${(typeof positionOffset.y === 'string') ? positionOffset.y : positionOffset.y + unitSuffix}`;
    translation = `translate(${defaultX}, ${defaultY})` + translation;
  }
  return translation;
}
```

I haven't tested this, just wrote it inline. Is there an easier / better / already supported way?

I tried using the scale property, but either I'm using it wrong or it doesn't work in my case. ATM I have my application scaled to ~13px so everything on the "canvas" fits the screen. That means that items on the canvas (draggable) are 0.8102232667450059% of their full size, and I used that as the scale value. The item is supposed to be at the bottom of the canvas, but instead of that, it's outside, not visible. If I scale my app to 100%, it's where it's supposed to be. 

If I manually convert the pixels in the transform to rem, everything works as expected. So I'd just like to use rem, if that's possible. 

I don't know if my use case is somewhat special or not. It's a "design your own product" kind of app.  Instead of working top-left, my app works bottom-center, meaning [0,0] is dead center on the canvas bottom axis. That way I don't have to deal with repositioning everything when screen size changes, or calculate where the center is. If I want an element 200px on the left, I set x to -200. If I want it 50px from the bottom, I set y to 50. Don't know if that messes with the internal calculations of this component, but FYI.

### PR DESCRIPTION
**Pull request by k1sul1**
As promised! :) I figured that instead of adding a wall of text, I'd just add it to the example gallery instead.

### CODE REVIEW

**Comment by k1sul1** [comment]
I have no idea why the Travis build failed, since I didn't touch package.json or yarn.lock. All tests succeeded locally.

```
yarn run v1.22.0
$ make test
[34mℹ[39m [90m｢wdm｣[39m: Hash: [1ma637f3826dabe1c42ba1[39m[22m
Version: webpack [1m4.43.0[39m[22m
Time: [1m1758[39m[22mms
Built at: 05/15/2020 [1m3:30:30 PM[39m[22m
                  [1mAsset[39m[22m      [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m       [1mChunk Names[39m[22m
 [1m[33mreact-draggable.min.js[39m[22m  [1m[33m1.01 MiB[39m[22m       [1m0[39m[22m  [1m[32m[emitted][39m[22m  [1m[33m[big][39m[22m  react-draggable.min
[1m[33mspecs/draggable.spec.js[39m[22m  [1m[33m2.45 MiB[39m[22m       [1m1[39m[22m  [1m[32m[emitted][39m[22m  [1m[33m[big][39m[22m  specs/draggable.spec
Entrypoint [1mreact-draggable.min[39m[22m [1m[33m[big][39m[22m = [1m[32mreact-draggable.min.js[39m[22m
Entrypoint [1mspecs/draggable.spec[39m[22m [1m[33m[big][39m[22m = [1m[32mspecs/draggable.spec.js[39m[22m
 [0] [1m./node_modules/prop-types/index.js[39m[22m 710 bytes {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
 [1] [1m./node_modules/react/index.js[39m[22m 190 bytes {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
 [2] [1m./node_modules/react-dom/index.js[39m[22m 1.33 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
 [7] [1m./node_modules/classnames/index.js[39m[22m 1.17 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
 [8] [1m./lib/cjs.js[39m[22m 508 bytes {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
 [9] [1m./node_modules/react/cjs/react.development.js[39m[22m 59.2 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[12] [1m./node_modules/react-dom/cjs/react-dom.development.js[39m[22m 839 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[17] [1m./node_modules/power-assert/index.js[39m[22m 2.2 KiB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[18] [1m./node_modules/react-dom/test-utils.js[39m[22m 220 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[19] [1m./lib/Draggable.js + 5 modules[39m[22m 56.4 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     | [1m./lib/Draggable.js[39m[22m 20.5 KiB[1m[32m [built][39m[22m
     | [1m./lib/utils/shims.js[39m[22m 945 bytes[1m[32m [built][39m[22m
     | [1m./lib/utils/domFns.js[39m[22m 8.9 KiB[1m[32m [built][39m[22m
     | [1m./lib/utils/positionFns.js[39m[22m 5 KiB[1m[32m [built][39m[22m
     | [1m./lib/utils/log.js[39m[22m 144 bytes[1m[32m [built][39m[22m
     | [1m./lib/DraggableCore.js[39m[22m 21 KiB[1m[32m [built][39m[22m
[22] [1m./lib/utils/getPrefix.js[39m[22m 1.66 KiB {[1m[33m0[39m[22m} {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[47] [1m./node_modules/react-test-renderer/shallow.js[39m[22m 234 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[48] [1m./node_modules/lodash/lodash.js[39m[22m 528 KiB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[63] [1m./node_modules/react-frame-component/lib/index.js[39m[22m 683 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[90] [1m./specs/draggable.spec.jsx[39m[22m 257 KiB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
    + 192 hidden modules
[34mℹ[39m [90m｢wdm｣[39m: Compiled successfully.
[32m15 05 2020 15:30:30.485:INFO [karma-server]: [39mKarma v4.4.1 server started at http://0.0.0.0:9876/
[32m15 05 2020 15:30:30.486:INFO [launcher]: [39mLaunching browsers Firefox, ChromeHeadless with concurrency unlimited
[32m15 05 2020 15:30:30.490:INFO [launcher]: [39mStarting browser Firefox
[32m15 05 2020 15:30:30.527:INFO [launcher]: [39mStarting browser ChromeHeadless
[32m15 05 2020 15:30:31.392:INFO [HeadlessChrome 81.0.4044 (Linux 0.0.0)]: [39mConnected on socket h8Fxefa7TPecfkXVAAAA with id 44785600
HeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 0 of 50[32m SUCCESS[39m (0 secs / 0 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 1 of 50[32m SUCCESS[39m (0 secs / 0.022 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 2 of 50[32m SUCCESS[39m (0 secs / 0.028 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 3 of 50[32m SUCCESS[39m (0 secs / 0.032 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 4 of 50[32m SUCCESS[39m (0 secs / 0.036 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 5 of 50[32m SUCCESS[39m (0 secs / 0.039 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 6 of 50[32m SUCCESS[39m (0 secs / 0.043 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 7 of 50[32m SUCCESS[39m (0 secs / 0.045 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 8 of 50[32m SUCCESS[39m (0 secs / 0.05 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 9 of 50[32m SUCCESS[39m (0 secs / 0.053 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 10 of 50[32m SUCCESS[39m (0 secs / 0.089 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 11 of 50[32m SUCCESS[39m (0 secs / 0.092 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 12 of 50[32m SUCCESS[39m (0 secs / 0.095 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 13 of 50[32m SUCCESS[39m (0 secs / 0.114 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 14 of 50[32m SUCCESS[39m (0 secs / 0.116 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 15 of 50[32m SUCCESS[39m (0 secs / 0.12 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 16 of 50[32m SUCCESS[39m (0 secs / 0.123 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 17 of 50[32m SUCCESS[39m (0 secs / 0.125 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 18 of 50[32m SUCCESS[39m (0 secs / 0.128 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 19 of 50[32m SUCCESS[39m (0 secs / 0.137 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 20 of 50[32m SUCCESS[39m (0 secs / 0.138 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 21 of 50[32m SUCCESS[39m (0 secs / 0.139 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 22 of 50[32m SUCCESS[39m (0 secs / 0.144 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 23 of 50[32m SUCCESS[39m (0 secs / 0.147 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 24 of 50[32m SUCCESS[39m (0 secs / 0.151 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 25 of 50[32m SUCCESS[39m (0 secs / 0.154 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 26 of 50[32m SUCCESS[39m (0 secs / 0.158 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 27 of 50[32m SUCCESS[39m (0 secs / 0.162 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 28 of 50[32m SUCCESS[39m (0 secs / 0.163 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 29 of 50[32m SUCCESS[39m (0 secs / 0.163 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 30 of 50[32m SUCCESS[39m (0 secs / 0.165 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 31 of 50[32m SUCCESS[39m (0 secs / 0.17 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 32 of 50[32m SUCCESS[39m (0 secs / 0.173 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 33 of 50[32m SUCCESS[39m (0 secs / 0.177 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 34 of 50[32m SUCCESS[39m (0 secs / 0.182 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 35 of 50[32m SUCCESS[39m (0 secs / 0.186 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 36 of 50[32m SUCCESS[39m (0 secs / 0.19 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 37 of 50[32m SUCCESS[39m (0 secs / 0.196 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 38 of 50[32m SUCCESS[39m (0 secs / 0.2 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 39 of 50[32m SUCCESS[39m (0 secs / 0.204 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 40 of 50[32m SUCCESS[39m (0 secs / 0.208 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 41 of 50[32m SUCCESS[39m (0 secs / 0.212 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 42 of 50[32m SUCCESS[39m (0 secs / 0.266 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 43 of 50[32m SUCCESS[39m (0 secs / 0.269 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 44 of 50[32m SUCCESS[39m (0 secs / 0.327 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 45 of 50[32m SUCCESS[39m (0 secs / 0.332 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 46 of 50[32m SUCCESS[39m (0 secs / 0.344 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 47 of 50[32m SUCCESS[39m (0 secs / 0.349 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 48 of 50[32m SUCCESS[39m (0 secs / 0.354 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 49 of 50[32m SUCCESS[39m (0 secs / 0.361 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0 secs / 0.366 secs)
[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
[32m15 05 2020 15:30:32.977:INFO [Firefox 74.0.0 (Linux 0.0.0)]: [39mConnected on socket -AdhoO1IK9MW6UQEAAAB with id 26878104

[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 0 of 50[32m SUCCESS[39m (0 secs / 0 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 1 of 50[32m SUCCESS[39m (0 secs / 0.045 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 2 of 50[32m SUCCESS[39m (0 secs / 0.117 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 3 of 50[32m SUCCESS[39m (0 secs / 0.121 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 4 of 50[32m SUCCESS[39m (0 secs / 0.132 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 5 of 50[32m SUCCESS[39m (0 secs / 0.146 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 6 of 50[32m SUCCESS[39m (0 secs / 0.156 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 7 of 50[32m SUCCESS[39m (0 secs / 0.166 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 8 of 50[32m SUCCESS[39m (0 secs / 0.171 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 9 of 50[32m SUCCESS[39m (0 secs / 0.177 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 10 of 50[32m SUCCESS[39m (0 secs / 0.185 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 11 of 50[32m SUCCESS[39m (0 secs / 0.192 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 12 of 50[32m SUCCESS[39m (0 secs / 0.201 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 13 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.211 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 14 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.214 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 15 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.22 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 16 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.227 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 17 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.291 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 18 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.295 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 19 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.306 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 20 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.308 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 21 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.314 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 22 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.321 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 23 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.327 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 24 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.331 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 25 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.344 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 26 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.349 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 27 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.406 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 28 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.463 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 29 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.472 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 30 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.48 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 31 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.491 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 32 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.507 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 33 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.511 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 34 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.516 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 35 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.522 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 36 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.527 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 37 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.532 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 38 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.533 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 39 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.533 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 40 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.539 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 41 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.544 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 42 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.553 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 43 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.559 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 44 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.566 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 45 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.574 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 46 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.582 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 47 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.586 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 48 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.589 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 49 of 50 (skipped 1)[32m SUCCESS[39m (0 secs / 0.593 secs)
[1A[2K[1A[2KHeadlessChrome 81.0.4044 (Linux 0.0.0): Executed 50 of 50[32m SUCCESS[39m (0.412 secs / 0.366 secs)
Firefox 74.0.0 (Linux 0.0.0): Executed 49 of 50 (skipped 1)[32m SUCCESS[39m (0.775 secs / 0.593 secs)
[32mTOTAL: 99 SUCCESS[39m
Done in 8.90s.
```

**Comment by k1sul1** [comment]
@STRML Updating the lockfile fixed 3 out of 4 builds. The special snowflake just can't do it. I don't know how to fix it. 

```
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error puppeteer@3.0.0: The engine "node" is incompatible with this module. Expected version ">=10.18.1". Got "8.17.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn --frozen-lockfile " failed. Retrying, 3 of 3.
```

**Comment by STRML** [comment]
After I merge #490, rebase on `master` and this should pass.

**Comment by k1sul1** [comment]
Done.

**Comment by STRML** [comment]
Thanks. Hoping we can create more some official extension points in the future.

**Pull request merged**
