### PR TITLE
[Enhancement] Support nodes within other frames

### PR DESCRIPTION
**Pull request by Craga89**
Added a `getOwnerDocument` utility that resolves the correct `document` based on the `DraggableCore`s associated DOMElement. This enables usage of `react-draggable` on nodes that are rendered within an `<iframe />`.

### CODE REVIEW

**Comment by STRML** [comment]
Hey, nicely done!

Could you add a quick test case for it?

**Comment by Craga89** [comment]
Hmmm, I'm not too up-to-date with the `TestUtils`! Currently using `react-frame-component` to render into an Iframe, so we'd probably need to do that, but since it uses the `unstable_renderSubtreeIntoContainer` ReactDOM utility not sure if it would work within the tests?

**Comment by Craga89** [comment]
Actually, maybe I just need to test that `getOwnerDocument` works as expected? That should be easy enough.

**Comment by STRML** [comment]
Yeah - rendering iframed components is a little crazy IMO and breaks all sorts of assumptions. To test it properly I don't mind installing react-frame-component as a devDep.

**Comment by Craga89** [comment]
:+1: I'll give it a shot when I get some time

**Comment by STRML** [comment]
Closing this in favor of #177 which also handles `window.getComputedStyle()`, which has problems with iframes.

**Comment by STRML** [comment]
Thanks anyhow for the contribution and I apologize that it got left here for this long.

**Pull request closed without merging**
