### PR TITLE
Scale parameter

### PR DESCRIPTION
**Pull request by wootencl**
@STRML This is the same as #217 but with the conflicts resolved (specifically the issues you had mentioned with `dist`). Hopefully that can give this the green light to be merged 🙂.

Credit goes to @Madisonw

### CODE REVIEW

**Comment by wootencl** [comment]
Hey @STRML, apologies for having to hit you with a notification but am curious if there's anything that's preventing this PR from being merged? Happy to make any required/needed changes.

**Comment by wootencl** [comment]
@STRML Bumping. Apologies again for the notification but would be super appreciative if this could be merged, or at minimum reviewed.

**Comment by cadrell0** [comment]
Is there an update on when this will be merged / release?

**Comment by wootencl** [comment]
@STRML Bumping to see if we can get this merged.

**Comment by chuyik** [comment]
I just made another package based on this pull request, anyone want it could install: 

```bash
npm install o2team-react-draggable
```

**Comment by iurii-zaitsev** [comment]
Thanks a lot! It's working! :)

**Pull request merged**
