### PR TITLE
Avoid having 'global' 'undefined'

### PR DESCRIPTION
**Pull request by amoilanen**
Tested that this change fixes the issue https://github.com/mzabriskie/react-draggable/issues/162 "Uncaught TypeError: Cannot read property 'SVGElement' of undefined"

Original changes were made by tkrkt in https://github.com/tkrkt/react-draggable/commit/41ec001671dec5c1afebecb5a8e984a13010f6a4 in a fork of react-draggable

Alternative approach is to avoid using global and assume that SVGElement can be defined as a global, instead of:

``` javascript
    if(typeof global.SVGElement !== 'undefined' && ReactDOM.findDOMNode(this) instanceof global.SVGElement) {
    ...
```

we can use

``` javascript
    if(typeof SVGElement !== 'undefined' && ReactDOM.findDOMNode(this) instanceof SVGElement) {
    ...
```

Please, note that after running webpack in Windows at the root the dist file has been changed somewhat, looks like line-endings were changed and not sure if source map has been properly generated, might be that we may need to run webpack to generate the dist in a Linux or Mac environment.

### CODE REVIEW

**Comment by STRML** [comment]
A few things:
1. This error only manifests when using babel on your node-modules folder - don't do that, tons of libraries break when you do.
2. This feels like a hack to me. I don't think it makes sense to introduce a dependency (and look, it has its own dependencies!) just to try to access the window.
3. Please don't add built files to PRs.

**Comment by amoilanen** [comment]
Hi, thank you for a quick reply.
1. It is true that this error only manifests itself when running node-modules through Babel however it might be necessary to do so if, for example, an older version of PhantomJS is used to run the unit tests.
2. Actually it is just explicitly requiring a used dependency instead of depending on the environment to provide it, i.e. instead of expecting to find 'SVGElement' in a window object we expect to find 'global' there.
3. There is a better solution: avoid referring to 'global'. If SVGElement is defined it should be defined in the global scope.

Updated the PR, removed the modifications to dist.

**Comment by STRML** [comment]
Seems good. Thanks.

**Comment by amoilanen** [comment]
Thanks

**Pull request merged**
