### PR TITLE
Use PropTypes from "prop-types" package instead of React one

### PR DESCRIPTION
**Pull request by dimkaufo**
Related to [issue](https://github.com/mzabriskie/react-draggable/issues/238)

### CODE REVIEW

**Comment by romamatusevich** [comment]
I have the same issue with the latest version of React. Hope this pull request will be merged soon.

**Comment by Pintouch** [comment]
Some news about this PR?
It's look like CI Env has changed on appveyor...

**Comment by STRML** [comment]
Thanks!

**Comment by STRML** [comment]
`2.2.4`

**Pull request merged**
