### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erfangc**
#122 clarifying how to import the component using a ES6 loader instead of browserify

### CODE REVIEW

**Comment by STRML** [comment]
This seems like a bug in jspm/SystemJS, not in React-Draggable. This community will continue to run into this issue again and again until they're able to handle babel-transpiled modules.

I'm not sure if I really understand the issue. Is jspm using dist/, not lib/?

**Comment by erfangc** [comment]
jspm is using lib/ it appears, but still need the .default to work

**Comment by STRML** [comment]
Ah, this is an older project so it is laid out slightly differently than I usually do now. 

Usually my layout is:

```
src/  <-- es6 files
lib/  <-- es5 files compiled with Babel for use with Node
dist/ <-- bundled files for use in browsers
```

But this project skips a step, using the `dist/` folder for both Node and Browser installs. This should be fine, though, and works just fine in Node.

I'm still not sure what JSPM is doing here to make it fail. See [this main export line](https://github.com/mzabriskie/react-draggable/blob/master/dist/react-draggable.js#L59), which requires from [this export](https://github.com/mzabriskie/react-draggable/blob/master/dist/react-draggable.js#L363). Notice the line after, where `module.exports` is assigned to `exports['default']`. So there shouldn't be an issue.

Some clues, perhaps: see [this issue](https://github.com/systemjs/systemjs/issues/304) talking about why SystemJS has decided not to detect `default` and require it.

**Comment by erfangc** [comment]
This is definitely a limitation of SystemJS import, one that may or may not have any relevance as module become more universally more ES6 like. It is not a big deal, just annoying and time consuming to debug the first couple of times.

**Comment by STRML** [comment]
Sure. Well, hell, doesn't hurt anything to put it in the README. Thanks @erfangc.

**Comment by STRML** [comment]
Actually, now that I think of it, wouldn't it make sense to just:

``` js
import ReactDraggable from 'react-draggable';
```

Does that not work? It makes sense that you'd have to access `.default` if you did an `import *`.

**Comment by erfangc** [comment]
Doesn't the react-draggable module export `DraggableCore` as well? I thought `import *` would seem cleaner and quicker ... but I suppose `import {ReactDraggable, DraggableCore}` works too? (haven't tested, will test and see if that works)

**Comment by STRML** [comment]
Would be:

``` js
import {default as Draggable, DraggableCore} from 'react-draggable';
```

I may back this out, this is just how ES6 loaders work, regardless of whether or not you're using SystemJS or Babel.

**Comment by erfangc** [comment]
make sense, thanks for that! I guess I didn't read the full spec.

**Pull request merged**
