### PR TITLE
Prefer named exports over default

### PR DESCRIPTION
**Pull request by TrySound**
This will be a breaking change, but I think it makes things cleaner. Also this allows as to distribute esm and cjs instead of umd as entry points.

### CODE REVIEW

**Comment by TrySound** [comment]
Friendly ping

/cc @STRML

**Comment by STRML** [comment]
This could break a lot of libs. I would strongly prefer to keep even something that is ugly rather than break backcompat.

**Comment by TrySound** [comment]
Can't we just make major release?

**Comment by TrySound** [comment]
I mean something ugly in esm will also break a lot of modules.

**Comment by TrySound** [comment]
I saw in a lot of code 
```js
import { DraggableCore } from 'react-draggable';
```
and it will be broken with esm format in react-draggable

**Comment by STRML** [comment]
Why would it break? I'm unfamiliar with releasing for esm given that it is not yet in wide use in node.

**Comment by TrySound** [comment]
@STRML esm is wide use in bundling. The problem is that with this vendor

```js
const Draggable = 1
Draggable.DraggableCore = 2

export default Draggable
```
is not possible to do this because `DraggableCore` is not named export
```js
import { DraggableCore } from 'react-draggable';
```

If we produce it as named export
```js
const Draggable = 1
const DraggableCore = 2
Draggable.DraggableCore = DraggableCore

export default Draggable
export {
  DraggableCore
}
```

then cjs output will look like
```js
exports.default = 1
exports.default.DraggableCore = 2
exports.DraggableCore = 2
```

so cjs will be broken.


The only way to fix this collision is to get rid from default exports

**Comment by TrySound** [comment]
Could you merge this?

**Comment by STRML** [comment]
I'm confused. Are we not waiting on:

> Just wait please until I provide cjs and esm bundles in the next PR.

**Comment by TrySound** [comment]
:)
> in the next PR

**Comment by TrySound** [comment]
I meant wait to release

**Pull request closed without merging**
