### PR TITLE
TransformScale is not applied properly while dragging an element #1046

### PR DESCRIPTION
**Pull request by serebrennikovalex**
Fixes: #1046 from react-grid-layout (https://github.com/STRML/react-grid-layout/issues/1046)

### CODE REVIEW

**Comment by serebrennikovalex** [comment]
@STRML @daynin please review these changes.

**Comment by STRML** [comment]
Code LGTM, could you please add a test?

**Comment by pahen** [comment]
Would be awesome if this can be merged soon @serebrennikovalex

**Comment by STRML** [comment]
Fixed in #438

**Pull request closed without merging**
