### PR TITLE
Add ability to pass in scale prop to correctly move draggable element at different scales

### PR DESCRIPTION
**Pull request by commanderking**
Based on this original PR: https://github.com/mzabriskie/react-draggable/pull/217/files, but removed conflicts with dist files. 

Also, added an additional test to check for scale prop and an example for the example page. Wasn't sure if we wanted the scale in DraggableCore, but can add it if desired. 

@STRML, let me know if any changes are needed and I can get them in Thanks for maintaining this awesome library!

### CODE REVIEW

**Comment by ibio** [comment]
This is really good idea! I'd like to use this feature as well.

**Comment by commanderking** [comment]
Hi @STRML, wondering whether there are any changes that need to be made to this PR for it to get merged in. Thanks again for all your work in maintaining this library!

**Comment by maixing** [comment]
When to add scale attribute?

**Comment by arnauddb** [comment]
Can we merge this PR ?

**Comment by STRML** [comment]
I'm wondering if this can be done automatically by querying the element's own effective scale. This could be on an on/off switch but would prevent the need for manually tweaking scale.

**Pull request closed without merging**
